### ISSUE TITLE
Latest PPA version not working on Ubuntu 14.10

### ISSUE THREAD

**Issue by fowlslegs** [micahflee/torbrowser-launcher#158]
Initializing Tor Browser Launcher
Successfully loaded mirrors from /usr/share/torbrowser-launcher/mirrors.txt
Warning: can't load mirrors from /home/fowlslegs/.config/torbrowser/mirrors.txt
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 69, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 118, in __init__
    self.start_launcher()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 152, in start_launcher
    self.run(False)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 638, in run
    subprocess.call([self.common.paths['tbb']['start']])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by micahflee** [comment]
There's been an issue with AppArmor profiles breaking things in Ubuntu. The Ubuntu releases of torbrowser-launcher no longer are shipped with AppArmor profiles, but you probably still have them on your system from an older install. Try doing this:

```sh
sudo apt-get purge torbrowser-launcher
sudo apt-get update
sudo apt-get install torbrowser-launcher
```

If you do that, do you still get the permission denied errors?

**Comment by fowlslegs** [comment]
Micah,

I managed to resolve this issue a while back (can't remember how unfortunately). Thanks for the response though.

Noah

Micah Lee:
