### ISSUE TITLE
"Permission Denied" on first install

### ISSUE THREAD

**Issue by Krishath** [micahflee/torbrowser-launcher#166]
I get this error after having pulled down your application from your Ubuntu repository:

```
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.8
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: chiave 63FEE659: "Erinn Clark <erinn@torproject.org>" non cambiata
gpg: Numero totale esaminato: 1
gpg:              non modificate: 1
gpg: chiave 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" non cambiata
gpg: Numero totale esaminato: 1
gpg:              non modificate: 1
Starting launcher dialog
LATEST VERSION 4.5a3
Checked for update within 24 hours, skipping
Latest version of TBB is installed, launching
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 69, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 118, in __init__
    self.start_launcher()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 152, in start_launcher
    self.run(False)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 637, in run
    subprocess.call([self.common.paths['tbb']['start'], '-allow-remote'] + self.url_list)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission Denied
```
If I try to execute it as root (and I shouldn't) I get:

```
No protocol specified
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.8
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 54, in main
    common = Common(tor_browser_launcher_version)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 52, in __init__
    self.build_paths()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 101, in build_paths
    self.set_gui('error', _("{0} is not writable").format(homedir), [], False)
AttributeError: Common instance has no attribute 'set_gui'
```

**Comment by nicholaswilkins** [comment]
I had same issue. I resolved it by running:
```bash
torbrowser-launcher --settings
```
then checking "check for updates next launch" and relaunching tor. I suspect tor got midway through its update cycle, then bailed because of permissions, leaving a nonfunctional application.

**Comment by micahflee** [comment]
I haven't been able to reproduce. But I believe with the recent patches this issue shouldn't happen anymore, anyway.
