### ISSUE TITLE
Updating over tor failure / manjaro linux

### ISSUE THREAD

**Issue by Gooberpatrol66** [micahflee/torbrowser-launcher#175]
Checking for update
Running task: download_update_check
Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
Updating over Tor
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/__init__.py", line 69, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 131, in __init__
    self.build_ui()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 285, in build_ui
    self.start(None)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 294, in start
    self.run_task()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 312, in run_task
    self.download('update check', self.common.paths['update_check_url'], self.common.paths['update_check_file'])
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 473, in download
    None)
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1927, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1560, in request
    endpoint = self._getEndpoint(parsedURI)
TypeError: _getEndpoint() takes exactly 4 arguments (2 given)

**Comment by micahflee** [comment]
This looks like an updating over Tor-related problem. If you open Tor Browser Settings and uncheck the box to update over Tor that should be a workaround. I haven't actually tested this in Arch before -- do you have a system tor service installed and running?

**Comment by Gooberpatrol66** [comment]
Disabling update over tor does make it work. I actually installed tor but i uninstalled it when i discovered this browser bundle, so no, unless something was left behind.

**Comment by micahflee** [comment]
It's a bit confusing, but Tor Browser Launcher needs to have a system Tor installed in the background to update over Tor. It's a chicken and egg problem-- when you first open Tor Browser Launcher it checks for updates and downloads one if it needs to, but this is before Tor Browser is open, so there isn't a Tor process to use except for the system Tor.

So yes, if you want updating over Tor to work you need to install the system Tor package as well.

However, you shouldn't feel too uneasy about updating over the clearnet. TBL does HTTPS certificate pinning when communicating to torproject.org, which means that even if you're the target of a MITM attack with a valid CA-signed cert, the attack will fail. And after downloading the new binary it verifies the gpg signature. The main benefit that updating over Tor gives you is that attackers won't even be able to tell that you're connecting to torproject.org and downloading a large file, all they'll see it Tor traffic.
