### ISSUE TITLE
TBB can't be launched

### ISSUE THREAD

**Issue by piotr-yuxuan** [micahflee/torbrowser-launcher#179]
Hello! First of all, thanks a lot for the work you've been doing on this piece of software.
I just come by to tell you back about an annoying issue I'm having. Let the code speak better than I could:
```
[user@Host-005 ~]$ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.9
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 0
Checking for update
Running task: download_update_check
Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
Updating over Tor
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/__init__.py", line 69, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 131, in __init__
    self.build_ui()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 285, in build_ui
    self.start(None)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 294, in start
    self.run_task()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 312, in run_task
    self.download('update check', self.common.paths['update_check_url'], self.common.paths['update_check_file'])
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 473, in download
    None)
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1926, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1559, in request
    endpoint = self._getEndpoint(parsedURI)
TypeError: _getEndpoint() takes exactly 4 arguments (2 given)
```
I'm running on GNU/Arch x64 and `pygtk` is installed on it.

**Comment by micahflee** [comment]
This looks like an updating over Tor-related problem. If you open Tor Browser Settings and uncheck the box to update over Tor that should be a workaround. I haven't actually tested this in Arch before -- do you have a system tor service installed and running?

**Comment by micahflee** [comment]
Actually, I think this is a duplicate if #175. Lemme post that comment there instead.
