### ISSUE TITLE
unable to install on fedora 21

### ISSUE THREAD

**Issue by tiagocasalribeiro** [micahflee/torbrowser-launcher#184]
I'm getting the following in the terminal, any ideas?

Running task: extract
Extracting tor-browser-linux64-4.5.1_en-US.tar.xz
Running task: run
Running /home/tiago/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/web/_newclient.py", line 911, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/web/_newclient.py", line 1462, in _finishResponse_WAITING
    self._giveUp(Failure(reason))
  File "/usr/lib64/python2.7/site-packages/twisted/web/_newclient.py", line 1515, in _giveUp
    self._disconnectParser(reason)
  File "/usr/lib64/python2.7/site-packages/twisted/web/_newclient.py", line 1503, in _disconnectParser
    parser.connectionLost(reason)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/web/_newclient.py", line 532, in connectionLost
    self.response._bodyDataFinished()
  File "/usr/lib64/python2.7/site-packages/twisted/web/_newclient.py", line 911, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/twisted/web/_newclient.py", line 1154, in _bodyDataFinished_CONNECTED
    self._bodyProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 378, in connectionLost
    self.all_done(reason)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 395, in response_finished
    self.run_task()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 332, in run_task
    self.verify()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 565, in verify
    self.run_task()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 336, in run_task
    self.extract()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 609, in extract
    self.run_task()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 340, in run_task
    self.run()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 640, in run
    subprocess.call([self.common.paths['tbb']['start']])
  File "/usr/lib64/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
exceptions.OSError: [Errno 2] No such file or directory

**Comment by shanemikel** [comment]
I've got the same problem

**Comment by rastus-vernon** [comment]
This should be fixed soon: https://bugzilla.redhat.com/show_bug.cgi?id=1226477.

**Comment by dtto** [comment]
I can confirm this same issue on debian jessie.

**Comment by rastus-vernon** [comment]
@dtto This is fixed in version 0.2, which is now in [jessie-backports](http://backports.debian.org/) and the updates repository for Fedora 22. You might want to enable jessie-backports and get it from there.

**Comment by dtto** [comment]
confirmed, works fine with 0.2.

**Comment by rastus-vernon** [comment]
@tiagocasalribeiro, @micahflee Can this bug be closed now?

**Comment by h01ger** [comment]
For the record, this is also fixed in Debian Jessie (no backports needed) in torbrowser-launcher 0.1.9-1+deb8u1 which carries the relevant patches from 0.2.0 which is in jessie-backports.

**Comment by shanemikel** [comment]
The fix has made it to fedora 21

**Comment by tiagocasalribeiro** [comment]
issue solved on fedora 21
