### ISSUE TITLE
Twisted chokes on unicode URL

### ISSUE THREAD

**Issue by pde** [micahflee/torbrowser-launcher#205]
rm -rf'ing ~/.local/share/torbrowser and running the latest vesion from git, I get:
```
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.1
https://github.com/micahflee/torbrowser-launcher
Updating over Tor
Checked for update within 24 hours, skipping
TBB is not installed, attempting to install 5.5a4-hardened
Downloading https://dist.torproject.org/torbrowser/5.5a4-hardened/tor-browser-linux64-5.5a4-hardened_en-US.tar.xz.asc
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 69, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 146, in __init__
    self.build_ui()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 304, in build_ui
    self.start(None)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 313, in start
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 338, in run_task
    self.download('signature', self.common.paths['sig_url'], self.common.paths['sig_file'])
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 485, in download
    None)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 1926, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 1557, in request
    parsedURI = URI.fromBytes(uri)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 606, in fromBytes
    scheme, netloc, path, params, query, fragment = http.urlparse(uri)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 160, in urlparse
    raise TypeError("url must be bytes, not unicode")
TypeError: url must be bytes, not unicode
```
Asking reportbug for some package versions:
```
Versions of packages torbrowser-launcher depends on:
ii  gnupg            1.4.18-7
ii  python-gtk2      2.24.0-4
ii  python-lzma      0.5.3-2+b1
ii  python-psutil    2.1.1-1+b1
ii  python-twisted   13.2.0-1
ii  python-txsocksx  1.13.0.3-1
pn  python:any       <none>
ii  tor              0.2.6.10-1
ii  wmctrl           1.07-7
ii  xz-utils         5.1.1alpha+20120614-2+b1

Versions of packages torbrowser-launcher recommends:
ii  python-pygame  1.9.1release+dfsg-10+b1
```

**Comment by pde** [comment]
```
dpkg -l *twisted*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                 Architecture            Description
+++-====================================-=======================-=======================-=============================================================================
ii  python-twisted                       13.2.0-1                all                     Event-based framework for internet applications (dependency package)
ii  python-twisted-bin                   15.2.1-1                amd64                   Event-based framework for internet applications
un  python-twisted-bin-dbg               <none>                  <none>                  (no description available)
ii  python-twisted-conch                 1:13.2.0-1              all                     Twisted SSH Implementation
ii  python-twisted-core                  15.2.1-1                all                     Event-based framework for internet applications
ii  python-twisted-lore                  13.2.0-1                all                     Documentation generator with HTML and LaTeX support
ii  python-twisted-mail                  13.2.0-1                all                     SMTP, IMAP and POP protocol implementation
ii  python-twisted-names                 13.2.0-1                all                     DNS protocol implementation with client and server
ii  python-twisted-news                  13.2.0-1                all                     NNTP protocol implementation with client and server
ii  python-twisted-runner                13.2.0-1                amd64                   Process management, including an inetd server
un  python-twisted-runner-dbg            <none>                  <none>                  (no description available)
ii  python-twisted-web                   15.2.1-1                all                     HTTP protocol implementation together with clients and servers
ii  python-twisted-words                 13.2.0-1                all                     Chat and Instant Messaging
un  python2.7-twisted                    <none>                  <none>                  (no description available)
```

**Comment by pde** [comment]
Upgrading all of those to 15.2.1-1 didn't help.  This looks like [this bug](https://github.com/twisted/treq/issues/54).

**Comment by pde** [comment]
cat ~/.config/torbrowser/settings.json
{"accept_links": false, "modem_sound": false, "latest_version": "5.5a4-hardened", "installed_version": "5.0.4", "check_for_updates": false, "mirror": "https://dist.torproject.org/", "tbl_version": "0.2.1", "update_over_tor": true, "last_update_check_timestamp": 1446830854}

**Comment by pde** [comment]
rm -rf'ing ~/.config/torbrowser, I now get:
```
torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.1
https://github.com/micahflee/torbrowser-launcher
Updating over Tor
Checking for update
Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 69, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 146, in __init__
    self.build_ui()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 304, in build_ui
    self.start(None)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 313, in start
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 330, in run_task
    self.download('update check', self.common.paths['update_check_url'], self.common.paths['update_check_file'])
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 485, in download
    None)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 1926, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 1559, in request
    endpoint = self._getEndpoint(parsedURI)
TypeError: _getEndpoint() takes exactly 4 arguments (2 given)
```

**Comment by pde** [comment]
And the recreated settings.json is:
```
cat ~/.config/torbrowser/settings.json 
{"installed_version": false, "check_for_updates": false, "modem_sound": false, "tbl_version": "0.2.1", "update_over_tor": true, "mirror": "https://dist.torproject.org/", "latest_version": "0", "last_update_check_timestamp": 0}
```

**Comment by micahflee** [comment]
Which Debian are you running?

**Comment by pde** [comment]
unstable

**Comment by tux3** [comment]
I'm experiencing the same issue, also on Debian sid.

**Comment by gbrennon** [comment]
Same issue on F22.

I've downloaded tor and torbrowser-launcher from dnf

**Comment by micahflee** [comment]
I'm not entirely sure where the unicode is coming from, but I believe I just fixed it regardless with these commits: https://github.com/micahflee/torbrowser-launcher/commit/1ff10552d0498d4f0edda6c27ab88a132fb52d57 https://github.com/micahflee/torbrowser-launcher/commit/94d184a26bb77f46e8256c23246fe68fa49552b0

Can someone experiencing this problem build `torbrowser-launcher` from the master branch and confirm that it's fixed?

**Comment by R1CH-T** [comment]
I just built the .deb package and installed on Ubuntu 15.10.
It updated immediately and launched the browser flawlessly.
Thanks for the fix. :)
Rich.

**Comment by micahflee** [comment]
Excellent!

**Comment by pde** [comment]
This appears to be working for me, though I'm waiting for a rather slow TBB download.
