### ISSUE TITLE
Crash on start if stdout is non-writeable

### ISSUE THREAD

**Issue by creideiki** [micahflee/torbrowser-launcher#298]
If `stdout` isn't writeable, `torbrowser-launcher` crashes on start. Running version 0.2.8 on Gentoo Linux.

I run KDE 5. Sometimes, the `plasmashell` process decides to eat all available memory, and has to be killed by running `kquitapp5 plasmashell && kstart5 plasmashell`. After doing this, `torbrowser-launcher` cannot be started from the program launcher until I log out and log in again.

I managed to provoke the same behaviour by starting `torbrowser-launcher` from a terminal, putting the process in the background, and immediately closing the terminal, i.e.
`torbrowser-launcher &` followed by `C-d`.

Running it under `strace` points to the output in `common.py:refresh_keyring`. `strace -o fail.log -s 256 -f /usr/bin/torbrowser-launcher &` ends with this failed write:
```
28908 write(1, "Keyring refreshed successfully...\n", 34) = -1 EIO (Input/output error)
```
Immediately followed by this Python backtrace:
```
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib64/python2.7/site-packages/torbrowser_launcher/__init__.py", line54, in main
    common = Common(tor_browser_launcher_version)
  File "/usr/lib64/python2.7/site-packages/torbrowser_launcher/common.py", line 80, in __init__
    self.init_gnupg()
  File "/usr/lib64/python2.7/site-packages/torbrowser_launcher/common.py", line 208, in init_gnupg
    self.import_keys()
  File "/usr/lib64/python2.7/site-packages/torbrowser_launcher/common.py", line 296, in import_keys
    self.refresh_keyring()
  File "/usr/lib64/python2.7/site-packages/torbrowser_launcher/common.py", line 229, in refresh_keyring
    print('Keyring refreshed successfully...\\n  No key updates for key: ' + fingerprint)
IOError: [Errno 5] Input/output error
```

Curiously, previous output from the Python code also fails, but non-fatally:
```
28908 write(1, "Tor Browser Launcher\n", 21) = -1 EIO (Input/output error)
28908 write(1, "By Micah Lee, licensed under MIT\n", 33) = -1 EIO (Input/output error)
28908 write(1, "version 0.2.8\n", 14)   = -1 EIO (Input/output error)
28908 write(1, "https://github.com/micahflee/torbrowser-launcher\n", 49) = -1 EIO (Input/output error)
```

**Comment by creideiki** [comment]
The culprit seems to be the `\n` in the middle of the argument to `print()`.

Test program:
```
#!/bin/env python2.7
import time
time.sleep(5)
print('A')
print('B\nC')
print('D')
```
Run it under `strace` and close the controlling terminal while it is sleeping:
```
$ strace -s 256 -o fatal.log -f ./fatal.py &
[1] 15573
^d
```
and the log says it crashes in the middle of the second `print()` call:
```
$ grep write fatal.log
15577 write(1, "A\n", 2)                = -1 EIO (Input/output error)
15577 write(1, "B\n", 2)                = -1 EIO (Input/output error)
15577 write(2, "Traceback (most recent call last):\n", 35) = -1 EIO (Input/output error)
15577 write(2, "  File \"./fatal.py\", line 5, in <module>\n", 41) = -1 EIO (Input/output error)
15577 write(2, "    ", 4)               = -1 EIO (Input/output error)
15577 write(2, "print('B\\nC')\n", 14)  = -1 EIO (Input/output error)
15577 write(2, "IOError", 7)            = -1 EIO (Input/output error)
15577 write(2, ": ", 2)                 = -1 EIO (Input/output error)
15577 write(2, "[Errno 5] Input/output error", 28) = -1 EIO (Input/output error)
15577 write(2, "\n", 1)                 = -1 EIO (Input/output error)
```

**Comment by creideiki** [comment]
Sure enough, the crashes go away if I split the `print()` statements at newlines:
```diff
--- torbrowser_launcher/common.py.orig  2017-12-16 10:04:18.375890560 +0100
+++ torbrowser_launcher/common.py       2017-12-16 10:04:48.195009187 +0100
@@ -226,9 +226,11 @@
             if match and match.group(2) == 'IMPORT_OK':
                 fingerprint = str(match.group(4))
                 if match.group(3) == '0':
-                    print('Keyring refreshed successfully...\n  No key updates for key: ' + fingerprint)
+                    print('Keyring refreshed successfully...')
+                    print('  No key updates for key: ' + fingerprint)
                 elif match.group(3) == '4':
-                    print('Keyring refreshed successfully...\n  New signatures for key: ' + fingerprint)
+                    print('Keyring refreshed successfully...')
+                    print('  New signatures for key: ' + fingerprint)
                 else:
                     print('Keyring refreshed successfully...')
 
```

**Comment by creideiki** [comment]
Upstream issue: https://bugs.python.org/issue32345

**Comment by micahflee** [comment]
Thanks for tracking this bug down.
