### ISSUE TITLE
torbrowser 7.5 cannot be installed by torbrowser-launcher

### ISSUE THREAD

**Issue by crocket** [micahflee/torbrowser-launcher#306]
When I execute 'torbrowser-launcher', I get the following error message, and torbrowser-launcher hangs.

```
exceptions.IOError: [Errno 2] No such file or directory: '/home/xxx/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'
```

**Comment by omgp84** [comment]
Same here.

```
Traceback (most recent call last):
File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 62, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 91, in __init__
    if not self.common.settings['installed'] or not self.check_min_version():
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 603, in check_min_version
    for line in open(self.common.paths['tbb']['versions']).readlines():
IOError: [Errno 2] No such file or directory: '/home/XXXXXXX/.local/share/torbrowser/tbb/x86_64/tor-browser_en-EN/Browser/TorBrowser/Docs/sources/versions'
```

Workaround: Run '/home/your_user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-EN/start-tor-browser.desktop' (this path may be different on other setups).

**Comment by u451f** [comment]
This is the corresponding Debian Bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888236

**Comment by AsciiWolf** [comment]
Fedora bug report: https://github.com/micahflee/torbrowser-launcher/issues/306

**Comment by AsciiWolf** [comment]
Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1538088

**Comment by shirishag75** [comment]
@omgp84 thank you for the workaround but this specific workaround people have had to use from one year now. Every couple of updates the same link breaks and takes with it all the passwords etc. Also it seems somewhat of a lost cause as the developer hasn't committed for torbrowser-launcher anything after 22nd June 2017. I do see his commits for onionshare but that's a different tool and functionality altogether.

**Comment by boklm** [comment]
https://trac.torproject.org/projects/tor/ticket/25012

**Comment by juengling** [comment]
I have the same issues since a couple of days before, breaking with an 'unhandled error' and then hanging endlessly in the progress dialogue.

Just for the protocol, and because it's not mentioned here yet, I see my launcher version is 0.2.7 on Ubuntu 17.10, while the newest tag in this repository is 0.2.8 since summer 2017.

**Comment by micahflee** [comment]
I just merged #307 which fixes this issue. I'll make a release with this fix soon

**Comment by behrangsa** [comment]
Facing the same issue on Ubuntu 17.10:

```
$ Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.7
https://github.com/micahflee/torbrowser-launcher
Downloading and installing Tor Browser for the first time.
Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
Latest version: 7.5
Downloading https://www.torservers.net/mirrors/torproject.org/dist/torbrowser/7.5/tor-browser-linux64-7.5_en-US.tar.xz.asc
Downloading https://www.torservers.net/mirrors/torproject.org/dist/torbrowser/7.5/tor-browser-linux64-7.5_en-US.tar.xz
Verifying Signature
Extracting tor-browser-linux64-7.5_en-US.tar.xz
Running /home/wazza/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 929, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1497, in _finishResponse_WAITING
    self._giveUp(Failure(reason))
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1550, in _giveUp
    self._disconnectParser(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1538, in _disconnectParser
    parser.connectionLost(reason)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 550, in connectionLost
    self.response._bodyDataFinished()
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 929, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1185, in _bodyDataFinished_CONNECTED
    self._bodyProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 329, in connectionLost
    self.all_done(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 346, in response_finished
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 276, in run_task
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 282, in run_task
    self.verify()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 491, in verify
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 286, in run_task
    self.extract()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 531, in extract
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 290, in run_task
    self.run()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 547, in run
    if not self.check_min_version():
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 535, in check_min_version
    for line in open(self.common.paths['tbb']['versions']).readlines():
exceptions.IOError: [Errno 2] No such file or directory: '/home/wazza/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'
```

**Comment by crocket** [comment]
@behrangsa It was fixed in torbrowser-launcher 0.2.9

**Comment by Warlock009** [comment]
Getting the same problem 
Can anyone help me how to fix this ??

**Comment by doug16rogers** [comment]
Workaround that worked for me:
```
    $ (cd .local/share/torbrowser/tbb/x86_64/tor-browser_en-US/; ./start-tor-browser.desktop)
    Launching './Browser/start-tor-browser --detach'...
```

**Comment by baptx** [comment]
You can just do @ViniciusBRodrigues @doug16rogers `~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/start-tor-browser`.

**Comment by majed17** [comment]
on linux mint 19.2 xfce i get 
```
Downloading and installing Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Download Error: Connection was refused by other side: 111: Connection refused. <class 'twisted.internet.error.ConnectionRefusedError'>

```
