### ISSUE TITLE
No module named lzma on Fedora 27

### ISSUE THREAD

**Issue by Yetoo1** [micahflee/torbrowser-launcher#311]
After running build_rpm.sh and installing the generated package, this error occured:
yetoo@yetoo-Inspiron-570:~/Documents/Others_Projects/torbrowser-launcher$ torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 29, in <module>
    import torbrowser_launcher
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/__init__.py", line 35, in <module>
    from .launcher import Launcher
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 37, in <module>
    import lzma
ImportError: No module named lzma

Solution: Install pyliblzma.
Better Solution: Make this a listed dependency for rpm based distros and fix build_rpm.sh to include such a change.

**Comment by Yetoo1** [comment]
I'm not sure if you want a pull request for something as small as this so here's the patch:
````
From f65b40a1e9daff72098a98d6080bdccbd05baa92 Mon Sep 17 00:00:00 2001
From: yetoo-desktop <yetoohappy@gmail.com>
Date: Mon, 29 Jan 2018 22:07:19 -0800
Subject: [PATCH] Fixed pyliblzma not being accounted for as a dependency

Added pyliblzma to be checked as a dependency in the generated rpm.
Added pyliblzma to the list of prequisites for rpm based distros.

https://github.com/micahflee/torbrowser-launcher/issues/311
---
 BUILD.md     | 2 +-
 build_rpm.sh | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/BUILD.md b/BUILD.md
index eaff7bc..09f0e5e 100644
--- a/BUILD.md
+++ b/BUILD.md
@@ -24,7 +24,7 @@ Optionally you can install `python-pygame` if you want to play a modem sound whi
 ### Red Hat, Fedora, CentOS, etc.
 
```sh
-sudo dnf install python-psutil python-twisted gnupg fakeroot rpm-build python-txsocksx tor pygtk2 python2-gpg
+sudo dnf install python-psutil python-twisted gnupg fakeroot rpm-build python-txsocksx tor pygtk2 python2-gpg pyliblzma
 ./build_rpm.sh
 sudo yum install dist/torbrowser-launcher-*.rpm
 ```
diff --git a/build_rpm.sh b/build_rpm.sh
index d51141a..e252f50 100755
--- a/build_rpm.sh
+++ b/build_rpm.sh
@@ -6,7 +6,7 @@ VERSION=`cat share/torbrowser-launcher/version`
 rm -r build dist
 
 # build binary package
-python setup.py bdist_rpm --requires="python-twisted, gnupg, fakeroot, pygtk2, python2-gpg"
+python setup.py bdist_rpm --requires="python-twisted, gnupg, fakeroot, pygtk2, python2-gpg, pyliblzma"
 
 # install it
 echo ""
-- 
2.14.3
````
