### ISSUE TITLE
Crash on Ubuntu 17.10

### ISSUE THREAD

**Issue by grigio** [micahflee/torbrowser-launcher#317]
```
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.7
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 62, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 70, in __init__
    if not self.common.settings['installed'] or not self.check_min_version():
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 535, in check_min_version
    for line in open(self.common.paths['tbb']['versions']).readlines():
IOError: [Errno 2] File o directory non esistente: '/home/grigio/.local/share/torbrowser/tbb/x86_64/tor-browser_it/Browser/TorBrowser/Docs/sources/versions'
```

**Comment by alassek** [comment]
This is already fixed in 0.2.9
