### ISSUE TITLE
Tor Browser does not start under Ubuntu 16.04

### ISSUE THREAD

**Issue by galahad0** [micahflee/torbrowser-launcher#340]
Launcher Przeglądarki Tora
By Micah Lee, licensed under MIT
wersja 0.2.9
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 56, in main
    common = Common(tor_browser_launcher_version)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 79, in __init__
    self.load_settings()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 326, in load_settings
    settings = json.load(open(self.paths['settings_file']))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by meltstone** [comment]
Same here. OpenSUSE Leap 15.0 Laptop: "Tor unexpectedly exited" and does not start, restarting is not helping. OpenSUSE Leap 15.0 Desktop (Tor not installed): "Downloading and installing for the first time.", stops at "Verifying Signature" and does not start.

**Comment by micahflee** [comment]
This is fixed in the new version 0.3.0 that I just released. You can get it by either [installing from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md) or installing from the Ubuntu PPA, described [here](https://github.com/micahflee/torbrowser-launcher/blob/develop/README.md#installing-in-ubuntu).
