### ISSUE TITLE
attribute error on start torbrowser

### ISSUE THREAD

**Issue by ghost** [micahflee/torbrowser-launcher#363]
Hi,

I do a fresh install of torbrowser on my debian stretch.
Using ` apt install torbrowser-launcher -t stretch-backports`

When i start from desktop icon a window open and close fastly.

When i try to launch from terminal here what's happen :

```
root@debian:/home/axel# torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 29, in <module>
    import torbrowser_launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 33, in <module>
    from .common import Common, SHARE
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 55, in <module>
    from twisted.internet import gtk2reactor
  File "/usr/lib/python2.7/dist-packages/twisted/internet/gtk2reactor.py", line 23, in <module>
    from twisted.internet import _glibbase
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_glibbase.py", line 20, in <module>
    from twisted.internet import base, posixbase, selectreactor
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 27, in <module>
    from twisted.internet._resolver import (
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_resolver.py", line 25, in <module>
    from twisted.internet.address import IPv4Address, IPv6Address
  File "/usr/lib/python2.7/dist-packages/twisted/internet/address.py", line 23, in <module>
    class IPv4Address(object):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/address.py", line 37, in IPv4Address
    type = attr.ib(validator=attr.validators.in_(["TCP", "UDP"]))
AttributeError: 'module' object has no attribute 'in_'

```

**Comment by NormanCarl** [comment]
+1 from me. Same behavior on strech-backports.
Same libaries installed on debian buster but working fine.

**Comment by AqwelF** [comment]
If its works for you could tell ma what do you have  in `usr/lib/python2.7/dist-packages/twisted/internet/address.py", line 37`

**Comment by AqwelF** [comment]
Welle i delete and clean conf files, `apt update ` and then install it again but without the `-t stretch-backports`and it works well !! Solve

**Comment by AqwelF** [comment]
/home/username/.local/share/torbrowser/
