### ISSUE TITLE
The repository 'http://ppa.launchpad.net/micahflee/ppa/ubuntu disco Release' does not have a Release file.

### ISSUE THREAD

**Issue by traumschule** [micahflee/torbrowser-launcher#385]
Hi @micahflee! Trying to reproduce #384 on debian stretch (stable) i ran into two issues.

```
root@debian# add-apt-repository ppa:micahflee/ppa
 This is where I release my Ubuntu software, including Tor Browser Launcher, OnionShare, and PDF Redact Tools.
 More info: https://launchpad.net/~micahflee/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp0in1p1iz/pubring.gpg' created
gpg: /tmp/tmp0in1p1iz/trustdb.gpg: trustdb created
gpg: key 4E72F77D7D158F33: public key "Launchpad PPA for Micah Lee" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.ssh'
```
This only happens on first run and looks like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867681.

```
root@debian# add-apt-repository ppa:micahflee/ppa
 This is where I release my Ubuntu software, including Tor Browser Launcher, OnionShare, and PDF Redact Tools.
 More info: https://launchpad.net/~micahflee/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmppzszpu28/pubring.gpg' created
gpg: /tmp/tmppzszpu28/trustdb.gpg: trustdb created
gpg: key 4E72F77D7D158F33: public key "Launchpad PPA for Micah Lee" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.

root@debian# apt update
Hit:1 tor://sdscoq7snqtznauu.onion/torproject.org stretch InRelease
Hit:2 tor://sdscoq7snqtznauu.onion/torproject.org tor-nightly-master-stretch InRelease
Ign:3 tor://ktqxbqrhg5ai2c7f.onion/debian-debug stretch-debug InRelease
Hit:4 tor://ktqxbqrhg5ai2c7f.onion/debian-debug stretch-debug Release
Ign:6 tor://vwakviie2ienjx6t.onion/debian stretch InRelease
Hit:7 tor://vwakviie2ienjx6t.onion/debian stretch-updates InRelease
Hit:8 tor://vwakviie2ienjx6t.onion/debian stretch-backports InRelease
Hit:9 tor://vwakviie2ienjx6t.onion/debian stretch Release
Ign:11 http://ppa.launchpad.net/micahflee/ppa/ubuntu disco InRelease
Err:12 http://ppa.launchpad.net/micahflee/ppa/ubuntu disco Release
  404  Not Found
Hit:13 tor://sgvtcaew4bxjd7ln.onion/debian-security stretch/updates InRelease
Reading package lists... Done                              
E: The repository 'http://ppa.launchpad.net/micahflee/ppa/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
https://ppa.launchpad.net/micahflee/ppa/ubuntu results in an 404 error here. This is bad because it leaves inexperienced users with `apt update` failing, the 'fix' (`rm /etc/apt/sources.list.d/micahflee-ubuntu-ppa-disco.list`) is probably not obvious to everyone.

```
root@debian# apt policy torbrowser-launcher
torbrowser-launcher:
  Installed: (none)
  Candidate: (none)
  Version table:

root@debian# cat /etc/apt/sources.list.d/micahflee-ubuntu-ppa-disco.list
deb http://ppa.launchpad.net/micahflee/ppa/ubuntu disco main
# deb-src http://ppa.launchpad.net/micahflee/ppa/ubuntu disco main
# deb-src http://ppa.launchpad.net/micahflee/ppa/ubuntu disco main

root@debian# cat /etc/debian_version
9.6
```

**Comment by davidbaumann** [comment]
Closed as the ppa is EOL.
