### ISSUE TITLE
Pickle load fails

### ISSUE THREAD

**Issue by CatusB** [micahflee/torbrowser-launcher#389]
I was using v0.1.9 for Debian Jessie. Migrated to Stretch and v0.3.1. By running torbrowser-launcher I get:

```
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.1
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/__init__.py", line 72, in main
    common = Common(tor_browser_launcher_version)
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 64, in __init__
    self.load_settings()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 313, in load_settings
    self.settings = pickle.load(open(self.paths['settings_file_pickle']))
TypeError: a bytes-like object is required, not 'str'
```
Conversion from old format fails. Line 313 should be:
`self.settings = pickle.load(open(self.paths['settings_file_pickle'], 'rb'))`

**Comment by Dolomich** [comment]
I had the same problem, turns out the old config file in /~/.config/torbrowser/ was causing it, deleting it allowed the launcher to work
