### ISSUE TITLE
Bad signature

### ISSUE THREAD

**Issue by randoclt** [micahflee/torbrowser-launcher#494]
KDE NEON TESTING
rando@rando-mnb:~$ sudo add-apt-repository ppa:micahflee/ppa
[sudo] Mot de passe de rando : 
 This is where I release my Ubuntu software, including Tor Browser Launcher, OnionShare, and PDF Redact Tools.
 More info: https://launchpad.net/~micahflee/+archive/ubuntu/ppa
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Réception de :1 file:/var/lib/preinstalled-pool focal InRelease
Ign :1 file:/var/lib/preinstalled-pool focal InRelease
Réception de :2 file:/var/lib/preinstalled-pool focal Release [3 949 B]
Réception de :2 file:/var/lib/preinstalled-pool focal Release [3 949 B]
Atteint :4 http://dl.google.com/linux/chrome/deb stable InRelease                     
Atteint :5 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  InRelease
Réception de :6 http://ppa.launchpad.net/micahflee/ppa/ubuntu focal InRelease [17,5 kB]
Atteint :7 https://brave-browser-apt-beta.s3.brave.com stable InRelease               
Atteint :8 http://archive.ubuntu.com/ubuntu focal InRelease                           
Atteint :9 http://files.eid.belgium.be/debian focal InRelease                         
Réception de :10 http://archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]    
Atteint :11 http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu focal InRelease    
Réception de :12 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]  
Réception de :13 http://archive.neon.kde.org/testing focal InRelease [153 kB]         
Réception de :14 http://archive.ubuntu.com/ubuntu focal-proposed InRelease [265 kB]   
Réception de :15 http://ppa.launchpad.net/micahflee/ppa/ubuntu focal/main amd64 Packages [540 B]
Réception de :16 http://archive.ubuntu.com/ubuntu focal-backports InRelease [98,3 kB] 
Atteint :17 http://files2.eid.belgium.be/debian focal InRelease                       
Réception de :18 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [204 kB]
Réception de :19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [184 kB]
Réception de :20 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2 468 B]
Réception de :21 http://archive.ubuntu.com/ubuntu focal-proposed/main amd64 DEP-11 Metadata [19,7 kB]
Réception de :22 http://archive.ubuntu.com/ubuntu focal-proposed/universe amd64 DEP-11 Metadata [31,4 kB]
Réception de :23 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1 976 B]
Réception de :24 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [24,3 kB]
Réception de :25 http://security.ubuntu.com/ubuntu focal-security/main DEP-11 48x48 Icons [11,0 kB]
Réception de :26 http://security.ubuntu.com/ubuntu focal-security/main DEP-11 64x64 Icons [16,5 kB]
Réception de :27 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [52,3 kB]
1 300 ko réceptionnés en 1s (934 ko/s)                               
Lecture des listes de paquets... Fait
rando@rando-mnb:~$ sudo apt update
Réception de :1 file:/var/lib/preinstalled-pool focal InRelease
Ign :1 file:/var/lib/preinstalled-pool focal InRelease
Réception de :2 file:/var/lib/preinstalled-pool focal Release [3 949 B]
Réception de :2 file:/var/lib/preinstalled-pool focal Release [3 949 B]
Atteint :4 http://ppa.launchpad.net/micahflee/ppa/ubuntu focal InRelease              
Atteint :5 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  InRelease
Atteint :6 http://dl.google.com/linux/chrome/deb stable InRelease                     
Atteint :7 http://files.eid.belgium.be/debian focal InRelease                         
Atteint :8 http://files2.eid.belgium.be/debian focal InRelease                        
Atteint :9 https://brave-browser-apt-beta.s3.brave.com stable InRelease               
Atteint :10 http://archive.ubuntu.com/ubuntu focal InRelease                          
Atteint :11 http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu focal InRelease    
Atteint :12 http://archive.ubuntu.com/ubuntu focal-updates InRelease                  
Atteint :13 http://security.ubuntu.com/ubuntu focal-security InRelease                
Atteint :14 http://archive.ubuntu.com/ubuntu focal-proposed InRelease 
Atteint :15 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Réception de :16 http://archive.neon.kde.org/testing focal InRelease [153 kB]
153 ko réceptionnés en 1s (159 ko/s) 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Tous les paquets sont à jour.
rando@rando-mnb:~$ sudo apt install torbrowser-launcher
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
Les NOUVEAUX paquets suivants seront installés :
  torbrowser-launcher
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/45,8 ko dans les archives.
Après cette opération, 184 ko d'espace disque supplémentaires seront utilisés.
Sélection du paquet torbrowser-launcher précédemment désélectionné.
(Lecture de la base de données... 210056 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../torbrowser-launcher_0.3.2-9_amd64.deb ...
Dépaquetage de torbrowser-launcher (0.3.2-9) ...
Paramétrage de torbrowser-launcher (0.3.2-9) ...
Traitement des actions différées (« triggers ») pour mime-support (3.64ubuntu1) ...
Traitement des actions différées (« triggers ») pour man-db (2.9.1-1) ...
Not building database; man-db/auto-update is not 'true'.
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.24-1ubuntu3) ...
rando@rando-mnb:~$ torbrowser-launcher
Tor Browser Launcher
Par Micah Lee, sous licence MIT
version 0.3.2
https://github.com/micahflee/torbrowser-launcher
Téléchargement du Navigateur Tor pour la première fois.
Téléchargement https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Dernière version : 9.5.4
Téléchargement https://tor.ccc.de/dist/torbrowser/9.5.4/tor-browser-linux64-9.5.4_en-US.tar.xz.asc
Téléchargement https://tor.ccc.de/dist/torbrowser/9.5.4/tor-browser-linux64-9.5.4_en-US.tar.xz
Vérification de la signature
Refreshing local keyring...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 589, in verify
    c.verify(signature=sig, signed_data=signed)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 541, in verify
    raise errors.BadSignatures(results[1], results=results)
gpg.errors.BadSignatures: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Clef expirée

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 600, in run
    verify()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 594, in verify
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 603, in run
    self.common.refresh_keyring()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 196, in refresh_keyring
    p = subprocess.Popen(['/usr/bin/gpg2', '--status-fd', '2',
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/usr/bin/gpg2'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/var/crash/_usr_bin_torbrowser-launcher.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 589, in verify
    c.verify(signature=sig, signed_data=signed)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 541, in verify
    raise errors.BadSignatures(results[1], results=results)
gpg.errors.BadSignatures: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Clef expirée

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 600, in run
    verify()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 594, in verify
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 603, in run
    self.common.refresh_keyring()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 196, in refresh_keyring
    p = subprocess.Popen(['/usr/bin/gpg2', '--status-fd', '2',
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/usr/bin/gpg2'
rando@rando-mnb:~$

**Comment by randoclt** [comment]
Solution trouvée plus bas

wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"
