### ISSUE TITLE
Can't run tor browser at Parrot

### ISSUE THREAD

**Issue by tanjilk** [micahflee/torbrowser-launcher#551]
```
└──╼ $torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.2
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Latest version: 10.0.13
Downloading https://dist.torproject.org/torbrowser/10.0.13/tor-browser-linux64-10.0.13_en-US.tar.xz.asc
Downloading https://dist.torproject.org/torbrowser/10.0.13/tor-browser-linux64-10.0.13_en-US.tar.xz
Verifying Signature
Refreshing local keyring...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 589, in verify
    c.verify(signature=sig, signed_data=signed)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 541, in verify
    raise errors.BadSignatures(results[1], results=results)
gpg.errors.BadSignatures: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 600, in run
    verify()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 594, in verify
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 603, in run
    self.common.refresh_keyring()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 206, in refresh_keyring
    p = subprocess.Popen(['/usr/bin/gpg2', '--status-fd', '2',
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/gpg2'
Aborted
```

**Comment by tanjilk** [comment]
As #493 i tried to run `wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"`
I got the same error

```
--2021-03-10 16:44:28--  https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sysrqb/torbrowser-launcher/develop/share/torbrowser-launcher/tor-browser-developers.asc [following]
--2021-03-10 16:44:29--  https://raw.githubusercontent.com/sysrqb/torbrowser-launcher/develop/share/torbrowser-launcher/tor-browser-developers.asc
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3470642 (3,3M) [application/octet-stream]
Saving to: ‘tor-browser-developers.asc.2’

tor-browser-developers.asc.2 100%[=============================================>]   3,31M   890KB/s    in 3,6s    

2021-03-10 16:44:33 (954 KB/s) - ‘tor-browser-developers.asc.2’ saved [3470642/3470642]

'/home/tanjilkh/tor-browser-developers.asc' -> '/usr/share/torbrowser-launcher/tor-browser-developers.asc'
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.2
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Latest version: 10.0.13
Downloading https://dist.torproject.org/torbrowser/10.0.13/tor-browser-linux64-10.0.13_en-US.tar.xz.asc
Downloading https://dist.torproject.org/torbrowser/10.0.13/tor-browser-linux64-10.0.13_en-US.tar.xz
Verifying Signature
Refreshing local keyring...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 589, in verify
    c.verify(signature=sig, signed_data=signed)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 541, in verify
    raise errors.BadSignatures(results[1], results=results)
gpg.errors.BadSignatures: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 600, in run
    verify()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 594, in verify
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 603, in run
    self.common.refresh_keyring()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 206, in refresh_keyring
    p = subprocess.Popen(['/usr/bin/gpg2', '--status-fd', '2',
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/gpg2'
Aborted
DONE
```

**Comment by tanjilk** [comment]
Corrected with these following steps

- `sudo apt install flatpak`
- `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
- `flatpak install flathub com.github.micahflee.torbrowser-launcher`
- `flatpak run com.github.micahflee.torbrowser-launcher`
