### ISSUE TITLE
v0.3.5 build error under Debian Buster

### ISSUE THREAD

**Issue by rogers0** [micahflee/torbrowser-launcher#587]
Although it build well under Debian Sid (unstable), it build error under Debian Buster (stable).
I guess it's because of python version.

```
ERROR: torbrowser_launcher (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: torbrowser_launcher
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/build/torbrowser-launcher-0.3.5/.pybuild/pythonX.Y_3.5/build/torbrowser_launcher/__init__.py", line 36, in <module>
    from .common import Common, SHARE
  File "/build/torbrowser-launcher-0.3.5/.pybuild/pythonX.Y_3.5/build/torbrowser_launcher/common.py", line 320
    print(f"Error fetching key, status code = {r.status_code}")
                                                             ^
SyntaxError: invalid syntax
```

Removing the "f" before string can fix this issue.
```
--- a/torbrowser_launcher/common.py
+++ b/torbrowser_launcher/common.py
@@ -317,7 +317,7 @@ class Common(object):
             proxies=self.proxies(),
         )
         if r.status_code != 200:
-            print(f"Error fetching key, status code = {r.status_code}")
+            print("Error fetching key, status code = {r.status_code}")
         else:
             with open(self.paths["signing_keys"]["wkd_tmp"], "wb") as f:
                 f.write(r.content)
```

**Comment by AsciiWolf** [comment]
Yeah, as far as I know, the f-string is in Python since 3.6.

**Comment by AsciiWolf** [comment]
Yeah, as far as I know, f-string was added in Python 3.6.
