### ISSUE TITLE
Unable to initialize program

### ISSUE THREAD

**Issue by genesis-kbm** [micahflee/torbrowser-launcher#597]
```
flatpak run com.github.micahflee.torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/app/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/app/lib/python3.8/site-packages/torbrowser_launcher/__init__.py", line 76, in main
    common = Common(tor_browser_launcher_version)
  File "/app/lib/python3.8/site-packages/torbrowser_launcher/common.py", line 61, in __init__
    self.discover_arch_lang()
  File "/app/lib/python3.8/site-packages/torbrowser_launcher/common.py", line 123, in discover_arch_lang
    locale.setlocale(locale.LC_MESSAGES, "")
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```

**Comment by zer0-x** [comment]
I don't know if it will work with the flatpak version, but try to run those commands before running the launcher:
```bash
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
flatpak run com.github.micahflee.torbrowser-launcher
```
or you can do:
```bash
LC_ALL="en_US.UTF-8" LC_CTYPE="en_US.UTF-8" flatpak run com.github.micahflee.torbrowser-launcher
```
