### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by rustyx** [micahflee/torbrowser-launcher#647]
Starting **`torbrowser-launcher`** from the **Terminal** is working fine.

But starting "**Tor Browser**" from the **GUI** (KDE Plasma) silently fails, Tor browser never appears.

The traceback looks like this:

```
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.3
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/__init__.py", line 78, in main
    common = Common(tor_browser_launcher_version)
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 60, in __init__
    self.discover_arch_lang()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 122, in discover_arch_lang
    locale.setlocale(locale.LC_MESSAGES, '')
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by Max-Chaos** [comment]
Is there fix my wont start at all reinstalled withe removing data did not help any ideas seam to be locale issue maybe passing argument in flatseal ?
LOG :
`Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/app/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/__init__.py", line 76, in main
    common = Common(tor_browser_launcher_version)
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/common.py", line 61, in __init__
    self.discover_arch_lang()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/common.py", line 123, in discover_arch_lang
    locale.setlocale(locale.LC_MESSAGES, "")
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
`
Please help

**Comment by davidbaumann** [comment]
Please try the latest version https://github.com/micahflee/torbrowser-launcher/blob/main/BUILD.md
