### ISSUE TITLE
[flatpak on Guix system] Could not find a suitable TLS CA certificate bundle, invalid path:

### ISSUE THREAD

**Issue by oatmealm** [micahflee/torbrowser-launcher#649]
I'm seeing the following error trying to launch the app. The file `/home/xxx/.guix-profile/etc/ssl/certs/ca-certificates.crt` does exist and is accessible.

```
flatpak run com.github.micahflee.torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/launcher.py", line 556, in run
    r = requests.get(
  File "/app/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/app/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/app/lib/python3.9/site-packages/requests/adapters.py", line 460, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/app/lib/python3.9/site-packages/requests/adapters.py", line 263, in cert_verify
    raise OSError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /home/xxx/.guix-profile/etc/ssl/certs/ca-certificates.crt
```

**Comment by Erudition** [comment]
In Flatseal, try adding the environment variable $SSL_CERT_DIR=~/.guix-profile/etc/ssl/certs

**Comment by franzos** [comment]
This worked for me, for Arduino IDE on PantherX OS (guix):

```bash
SSL_CERT_DIR=/etc/ssl/certs flatpak run cc.arduino.IDE2
```

Resolved errors like ` failed to verify certificate: x509: certificate signed by unknown authority`.

**Comment by FuncProgLinux** [comment]
2025 and no updates.

On latest Guix: `flatpak override --user --env=SSL_CERT_DIR=~/.guix-profile/etc/ssl/certs org.torproject.torbrowser-launcher` doesn't work anymore as the program is still picking `/run/current-system/profile/etc/ssl/certs/ca-certificates.crt`

Use `guix install torbrowser` or add it to your user profile. If you need substitutes use `guix weather torbrowser` to see if any are available. The consequences of using  bloated & un-customizable package managers :/
