### ISSUE TITLE
sos: 404 download error

### ISSUE THREAD

**Issue by andres1968** [micahflee/torbrowser-launcher#663]
hi, I try TOR on Kali Linux and Parrot OS but said: error 404
I try on terminal command sudo … same error. any suggest.
many thanks and a hug for all best community

**Comment by tensornova** [comment]
hotfix: #660 

basically, follow this
[build from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md)

however, you just have to change the first command here to 
`git clone https://github.com/tensornova/torbrowser-launcher.git`

tell me if there is an error related to 'float' when you follow this.

**Comment by Relected** [comment]
yup 

```
Traceback (most recent call last):
  File "/home/relected/Downloads/git/tor-fuckup/torbrowser-launcher/./torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/home/relected/Downloads/git/tor-fuckup/torbrowser-launcher/torbrowser_launcher/__init__.py", line 92, in main
    gui.move(
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'
```

**Comment by tensornova** [comment]
Issue #628

then 
(1) if you've already installed it, please uninstall it or delete a directory `torbrowser-launcher` you downloaded before

(2) follow [build from souurse](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md)
but try `git clone -b hotfix --single-branch https://github.com/tensornova/torbrowser-launcher.git`
instead of the first command

**Comment by Relected** [comment]
hi, sorry for the long wait i was asleep

the spftware starts, but its stuck at 0% at downloading signatures

**Comment by PoorPocketsMcNewHold** [comment]
> Hi, I have the same problem, do you know a way to make it work with flatpak? Do I just need to wait for the flatpak to be updated? Thanks you

That's exact. First we need to have it being merged via #661, and then, that a new build is pushed to flatpak.

**Comment by svb300** [comment]
> Issue #628
> 
> then (1) if you've already installed it, please uninstall it or delete a directory `torbrowser-launcher` you downloaded before
> 
> (2) follow [build from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md) but try `git clone -b hotfix --single-branch https://github.com/tensornova/torbrowser-launcher.git` instead of the first command

Hey none of this worked for me at all. Take a look. I'm on Ubuntu 22.04. When will TOR be fixed?
```
computer@computer-System-Product-Name:~$ git clone https://github.com/tensornova/torbrowser-launcher.git
Command 'git' not found, but can be installed with:
sudo apt install git
computer@computer-System-Product-Name:~$ sudo apt install git clone https://github.com/tensornova/torbrowser-launcher.git
[sudo] password for computer: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package clone
E: Unable to locate package https://github.com/tensornova
computer@computer-System-Product-Name:~$ git clone -b hotfix --single-branch https://github.com/tensornova/torbrowser-launcher.git
Command 'git' not found, but can be installed with:
sudo apt install git
computer@computer-System-Product-Name:~$ sudo apt install git clone -b hotfix --single-branch https://github.com/tensornova/torbrowser-launcher.git
E: Command line option 'b' [from -b] is not understood in combination with the other options.
computer@computer-System-Product-Name:~$ git clone https://github.com/micahflee/torbrowser-launcher.git
Command 'git' not found, but can be installed with:
sudo apt install git
computer@computer-System-Product-Name:~$ sudo apt install git clone https://github.com/micahflee/torbrowser-launcher.git
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package clone
E: Unable to locate package https://github.com/micahflee
computer@computer-System-Product-Name:~$ 
```

**Comment by svb300** [comment]
I am also getting the "Download Error: 404"

When is this going to get fixed?

**Comment by tensornova** [comment]
> hi, sorry for the long wait i was asleep
> 
> ~the software starts, but its stuck at 0% at downloading signatures~
> 
> Edit: nvm it works, thanks
> 
> EDIT 2: it deleted all of my data! :(

um, sorry, I didnt considering update that is not a new installation. It's a guess, but it seems that the data has been deleted because the program path has changed even though the data exists. This command `remove` does not usually delete user configuration files and the data. I think it will be okay if you downgrade it.

**Comment by tensornova** [comment]
> > Issue #628
> > then (1) if you've already installed it, please uninstall it or delete a directory `torbrowser-launcher` you downloaded before
> > (2) follow [build from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md) but try `git clone -b hotfix --single-branch https://github.com/tensornova/torbrowser-launcher.git` instead of the first command
> 
> Hey none of this worked for me at all. Take a look. I'm on Ubuntu 22.04. When will TOR be fixed?
> 
> ```
> computer@computer-System-Product-Name:~$ git clone https://github.com/tensornova/torbrowser-launcher.git
> Command 'git' not found, but can be installed with:
> sudo apt install git
> computer@computer-System-Product-Name:~$ sudo apt install git clone https://github.com/tensornova/torbrowser-launcher.git
> [sudo] password for computer: 
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package clone
> E: Unable to locate package https://github.com/tensornova
> computer@computer-System-Product-Name:~$ git clone -b hotfix --single-branch https://github.com/tensornova/torbrowser-launcher.git
> Command 'git' not found, but can be installed with:
> sudo apt install git
> computer@computer-System-Product-Name:~$ sudo apt install git clone -b hotfix --single-branch https://github.com/tensornova/torbrowser-launcher.git
> E: Command line option 'b' [from -b] is not understood in combination with the other options.
> computer@computer-System-Product-Name:~$ git clone https://github.com/micahflee/torbrowser-launcher.git
> Command 'git' not found, but can be installed with:
> sudo apt install git
> computer@computer-System-Product-Name:~$ sudo apt install git clone https://github.com/micahflee/torbrowser-launcher.git
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package clone
> E: Unable to locate package https://github.com/micahflee
> computer@computer-System-Product-Name:~$ 
> ```

not `sudo apt install git clone` but `sudo apt install git`

**Comment by Relected** [comment]
@tensornova 

> um, sorry, I didnt considering update that is not a new installation. It's a guess, but it seems that the data has been deleted because a path to the data has changed even though the data exists. I'll check it out and let you know if I can. and i recommend a downgrade if you are able to do it

thats reassuring, BTW what was the old location of the browser profile, maybe I can recover it manually?

**Comment by narcisgarcia** [comment]
I failed with torbrowser-launcher from Debian Stable too.
I think an update should be released through OS distributions.

**Comment by Relected** [comment]
it will slowly happen, just wait for it slowly

also Debian Stable will take a pretty long time to upate torbrowser-laucher so i think the bestthing to do rn is to install it maually

**Comment by markmaker** [comment]
This is no solution, but info towards one.

Tor seems tor has moved to a universal language package in 12.0.1.

So the launcher should not use the language to composite the download path, instead it should use "ALL".

open the `/usr/lib/python3/dist-packages/torbrowser_launcher/common.py` file

Change the `discover_arch_lang` function to simply set `self.language` to "ALL", i.e. delete all the complicated language guessing code that is there and replace it with one line (I also show the comment of the next function, so it becomes clear how far it has to be replaced):

```python
    # discover the architecture and language
    def discover_arch_lang(self):
        # figure out the architecture
        self.architecture = "x86_64" if "64" in platform.architecture()[0] else "i686"

        # figure out the language ... with 12.0.1 this has become a universal language package
        self.language = "ALL"

    # get value of environment variable, if it is not set return the default value

```

Now it downloads alright and tries to install ... where it hangs. 

```
Running /home/username/.local/share/torbrowser/tbb/x86_64/tor-browser_ALL/start-tor-browser.desktop
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 442, in success
    self.run_task()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 301, in run_task
    self.run()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 477, in run
    if not self.check_min_version():
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 465, in check_min_version
    for line in open(self.common.paths["tbb"]["changelog"], "rb").readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/home/markus/.local/share/torbrowser/tbb/x86_64/tor-browser_ALL/Browser/TorBrowser/Docs/ChangeLog.txt'

```

Some sort of unfulfilled _promise_ or whatever the contraption is called in Python. 

So back to square one.

_Mark

**Comment by narcisgarcia** [comment]
Okay, I've done this step as a workaround for an installation:
```
sudo sed -i 's|self.language =.*|self.language = "ALL"|g' /usr/lib/python3/dist-packages/torbrowser_launcher/common.py
```
After this, on launching torbrowser-launcher it downloads successfully application's package, but it breaks with:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_ALL/Browser/TorBrowser/Docs/ChangeLog.txt'
```

Then, to complete workaround at user profile this must be run in a terminal:
```
mkdir -p ~/.local/share/torbrowser/tbb/x86_64
cd ~/.local/share/torbrowser/tbb/x86_64
ln - s tor-browser tor-browser_ALL
```
And it just works.
All this expecting torbrowser-launcher incorporates new fixes.

**Comment by SterlingButters** [comment]
Watching this issue also

**Comment by hellomelter234** [comment]
when using flatpak i get this error:

> qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

**Comment by SterlingButters** [comment]
> also when i try tensornova's solution it requires my github username and password and then says that password authentication has been ended since august 2021.

You have to generate a token and use that as your password. Either way, when you do that you are (or I was) notified that the repository doesn't exist

**Comment by narcisgarcia** [comment]
> i tried to use source and debian repository but i got error 404. also when i try tensornova's solution it requires my github username and password and then says that password authentication has been ended since august 2021.

My workaround also works with Debian packaging source (first part to common.py , next part to postinst & skel)

**Comment by Relected** [comment]
its fixed, @narcisgarcia you just have to wait until the software is updated in your repo

or you can just manually install it

**Comment by atriox2510** [comment]
just build from source code and install the package created [https://github.com/micahflee/torbrowser-launcher/blob/main/BUILD.md](https://github.com/micahflee/torbrowser-launcher/blob/main/BUILD.md)

**Comment by Simx72** [comment]
Getting the 404 error after installing from ubuntu official repo
Build from source worked for me

**Comment by boklm** [comment]
> Getting the 404 error after installing from ubuntu official repo

What version of torbrowser-launcher did you get from this repo?
