### ISSUE TITLE
0.3.6 (debian testing) launch failed, fresh install

### ISSUE THREAD

**Issue by Amunhateb** [micahflee/torbrowser-launcher#664]
Seems like when guys were fixing download logic they forgot to check for folder exists or not. Should be a simple fix. For now it's easy as just:
$ mkdir -p /home/username/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64

Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.6
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/app/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/__init__.py", line 76, in main
    common = Common(tor_browser_launcher_version)
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/common.py", line 62, in __init__
    self.torbrowser12_rename_old_tbb()
  File "/app/lib/python3.9/site-packages/torbrowser_launcher/common.py", line 180, in torbrowser12_rename_old_tbb
    for filename in os.listdir(self.paths["tbb"]["dir"]):
FileNotFoundError: [Errno 2] No such file or directory: '/home/uesrname/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64'

**Comment by AsciiWolf** [comment]
Yep, I have also noticed this issue. We are working on a fix.

Temporary workaround is to run `mkdir -p ~/.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64`, then re-run the Tor Browser Launcher.

**Comment by AsciiWolf** [comment]
Should be fixed by 7472ff6b374eaed7382ae6016b516b84954c18e3. The update will be available on Flathub in a few hours.
