### ISSUE TITLE
start-tor-browser.desktop exists but isn't found

### ISSUE THREAD

**Issue by sonofevil** [micahflee/torbrowser-launcher#670]
```
 ~ $ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.6
https://github.com/micahflee/torbrowser-launcher
Launching Tor Browser.
Running /home/lutra/.local/share/torbrowser/tbb/x86_64/tor-browser/start-tor-browser.desktop
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/__init__.py", line 87, in main
    gui = Launcher(common, app, url_list)
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/launcher.py", line 167, in __init__
    self.update()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/launcher.py", line 214, in update
    self.start(None)
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/launcher.py", line 231, in start
    self.run_task()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/launcher.py", line 299, in run_task
    self.run()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/launcher.py", line 479, in run
    subprocess.call(
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lutra/.local/share/torbrowser/tbb/x86_64/tor-browser/start-tor-browser.desktop'

```

```
file /home/lutra/.local/share/torbrowser/tbb/x86_64/tor-browser/start-tor-browser.desktop
/home/lutra/.local/share/torbrowser/tbb/x86_64/tor-browser/start-tor-browser.desktop: a /usr/bin/env ./Browser/execdesktop script, Unicode text, UTF-8 text executable
```

How?

**Comment by davidbaumann** [comment]
How did you install torbrowser-launcher
And which distribution are running it on?

**Comment by sonofevil** [comment]
I am on EndeavourOS with Arch Linux repos.

I installed torbrowser-launcher with `yay -S torbrowser-launcher`

**Comment by davidbaumann** [comment]
You might want to delete `/home/lutra/.local/share/torbrowser/` and try again.
I just checked on a fresh install, but cannot confirm your problem.

Maybe check file permissions of `/home/lutra/.local/share/torbrowser/tbb/x86_64/tor-browser/start-tor-browser.desktop` first.

**Comment by sonofevil** [comment]
File permissions are rwxrwx--- and owner is me.

**Comment by prnflks** [comment]
Same here on Arch..  ../share/torbrowser removed; torbrowser-launcher and tor package removed and reinstalled. It started downloading then dropped the same No such File or directory error

**Comment by Lunc4** [comment]
Hey, I'm in the exact same scenario as you. I solved it by installing it from the website: https://www.torproject.org/download/
Removing the previous tor files:
rm -rf ~/.local/share/torbrowser/

Exctract the archive using:
tar xvf ./tor-browser-linux-x86_64-13.0.tar.xz
And then run the binary directly 
./tor-browser/Browser/start-tor-browser
