### ISSUE TITLE
torbrowser-launcher error

### ISSUE THREAD

**Issue by ibuetler** [micahflee/torbrowser-launcher#671]
Use torbrowser-launcher on. latest Kali. The `torbrowser-launcher` was not starting the TOR BROWSER. 

The python script was looking in the wrong folder. 

See my solution approach below

```
╭─ ~/.local/share/torbrowser                                                                                                                                                       ✔ 


╭─ ~                                                                                                                                                                               ✔ 
╰─ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Latest version: 12.0.1
Downloading https://dist.torproject.org/torbrowser/12.0.1/tor-browser-linux64-12.0.1_en-US.tar.xz.asc
Downloading https://dist.torproject.org/torbrowser/12.0.1/tor-browser-linux64-12.0.1_en-US.tar.xz
Verifying Signature
Extracting tor-browser-linux64-12.0.1_en-US.tar.xz
Running /home/hacker/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 442, in success
    self.run_task()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 301, in run_task
    self.run()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 477, in run
    if not self.check_min_version():
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 465, in check_min_version
    for line in open(self.common.paths["tbb"]["changelog"], "rb").readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/home/hacker/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/ChangeLog.txt'
[1]    20822 IOT instruction  torbrowser-launcher

╭─ ~                                                                                                                                                                      IOT ✘  11s 
╰─ cd .local/share/torbrowser/tbb/x86_64 

╭─ ~/.local/share/torbrowser/tbb/x86_64                                                                                                                                            ✔ 
╰─ ls -al 
total 12
drwx------ 3 hacker hacker 4096 Jan 11 13:27 .
drwxr-xr-x 3 hacker hacker 4096 Jan 11 13:27 ..
drwx------ 3 hacker hacker 4096 Jan  1  2000 tor-browser

SOLUTION BELOW: Soft-link to path the launcher expects

╭─ ~/.local/share/torbrowser/tbb/x86_64                                                                                                                                            ✔ 
╰─ ln -s tor-browser tor-browser_en-US

╭─ ~/.local/share/torbrowser/tbb/x86_64                                                                                                                                            ✔ 
╰─ ls -al 
total 12
drwx------ 3 hacker hacker 4096 Jan 11 13:34 .
drwxr-xr-x 3 hacker hacker 4096 Jan 11 13:27 ..
drwx------ 3 hacker hacker 4096 Jan  1  2000 tor-browser
lrwxrwxrwx 1 hacker hacker   11 Jan 11 13:34 tor-browser_en-US -> tor-browser

╭─ ~/.local/share/torbrowser/tbb/x86_64                                                                                                                                            ✔ 
╰─ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Launching Tor Browser.
Running /home/hacker/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
Launching './Browser/start-tor-browser --detach'...

╭─ ~/.local/share/torbrowser/tbb/x86_64                                                                                                                                            ✔ 
╰─ ls -al 
total 12
drwx------ 3 hacker hacker 4096 Jan 11 13:34 .
drwxr-xr-x 3 hacker hacker 4096 Jan 11 13:27 ..
drwx------ 3 hacker hacker 4096 Jan 11 13:35 tor-browser
lrwxrwxrwx 1 hacker hacker   11 Jan 11 13:34 tor-browser_en-US -> tor-browser

╭─ ~/.local/share/torbrowser/tbb/x86_64     
```

**Comment by davidbaumann** [comment]
Also a result of #659 .
