### ISSUE TITLE
 When trying to open Torbrowser-launcher through the terminal, it displays an error message and does not open. 

### ISSUE THREAD

**Issue by serial02** [micahflee/torbrowser-launcher#684]
Olá Pessoal

Hey guys

When trying to open Torbrowser-launcher through the terminal, it displays an error message and does not open.
Clicking on Tobrowser icons also does not open the browser.

Error message:
```

edson@localhost:~> torbrowser-launcher
Lançador do Navegador Tor
Por Micah Lee, licenciado sob o MIT
versão 0.3.6
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/__init__.py", line 76, in main
    common = Common(tor_browser_launcher_version)
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/common.py", line 62, in __init__
    self.torbrowser12_rename_old_tbb()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/common.py", line 185, in torbrowser12_rename_old_tbb
    os.rename(abs_filename, self.paths["tbb"]["dir_tbb"])
FileExistsError: [Errno 17] File exists: '/home/edson/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US' -> '/home/edson/.local/share/torbrowser/tbb/x86_64/tor-browser'
edson@localhost:~>
```
Sistema: 

![Captura de tela de 2023-04-01 16-03-11](https://user-images.githubusercontent.com/32621790/229309539-aaa2c708-bfd5-44a7-a8f8-67afd0cc41c0.png)

Torbrowser data by yast2

![Captura de tela de 2023-04-01 14-34-09](https://user-images.githubusercontent.com/32621790/229309581-273bd73a-e30f-4499-aa7a-31d456faef37.png)

**Comment by serial02** [comment]
Is there a possibility to update the version of torbrowser 12.04 ( tor-browser-linux64-12.0.4_ALL.tar.xz ) to openSuse Tumbleweed?


 The existing version is very out of date being 0.3.6.0.
