### ISSUE TITLE
Last Torbrowser-update broke the launcher

### ISSUE THREAD

**Issue by Krommyon** [micahflee/torbrowser-launcher#690]
Linux/Tumbleweed:

***@localhost:~> torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.6
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/__init__.py", line 87, in main
    gui = Launcher(common, app, url_list)
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/launcher.py", line 82, in __init__
    if not self.common.settings["installed"] or not self.check_min_version():
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/launcher.py", line 461, in check_min_version
    if version.parse(self.min_version) <= version.parse(installed_version):
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 196, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by Krommyon** [comment]
Today, I got an update for torbrowser-launcher to 0.3.6-1.3.
Yet I still get the following message:

***@localhost:~> torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.6
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3.11/site-packages/torbrowser_launcher/__init__.py", line 87, in main
    gui = Launcher(common, app, url_list)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torbrowser_launcher/launcher.py", line 82, in __init__
    if not self.common.settings["installed"] or not self.check_min_version():
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/torbrowser_launcher/launcher.py", line 461, in check_min_version
    if version.parse(self.min_version) <= version.parse(installed_version):
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 196, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
