### ISSUE TITLE
ImportError: Twisted requires zope.interface 3.6.0 or later.

### ISSUE THREAD

**Issue by azul** [micahflee/torbrowser-launcher#91]
I installed torbrowser-launcher on the latest ubuntu. It started fine the first time i tried it but now i get

```
$ torbrowser-launcher 
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 36, in <module>
    from twisted.internet import gtk2reactor
  File "/usr/lib/python2.7/dist-packages/twisted/__init__.py", line 53, in <module>
    _checkRequirements()
  File "/usr/lib/python2.7/dist-packages/twisted/__init__.py", line 40, in _checkRequirements
    raise ImportError(required + ".")
ImportError: Twisted requires zope.interface 3.6.0 or later.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python2.7/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python2.7/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/usr/lib/python2.7/dist-packages/apt/__init__.py", line 34, in <module>
    apt_pkg.init_config()
SystemError: E:Unable to read /etc/apt/apt.conf.d/ - opendir (13: Permission denied)

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 36, in <module>
    from twisted.internet import gtk2reactor
  File "/usr/lib/python2.7/dist-packages/twisted/__init__.py", line 53, in <module>
    _checkRequirements()
  File "/usr/lib/python2.7/dist-packages/twisted/__init__.py", line 40, in _checkRequirements
    raise ImportError(required + ".")
ImportError: Twisted requires zope.interface 3.6.0 or later.
```

I had twisted and zope.interface installed via pip and removed them. Still does not work for me though.

**Comment by dtto** [comment]
I am still not able to run on the latest Wheezy. Executing it through python as mentioned by azul, I now get a different error:
```
Latest version of TBB is installed, launching
Launching Tor Browser for Linux in .../tor-browser_en-US/Browser...
XPCOMGlueLoad error for file .../torbrowser/tbb/x86_64/tor-browser_en-US/Browser/libxul.so:
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/sunbird/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/libxul.so)
Couldn't load XPCOM.
Tor Browser exited abnormally.  Exit code: 255
```

**Comment by pde** [comment]
I've also encountered this problem.  AFAICT what is happening is that the import of Twisted causes the `pkg_resources` package to scan the user's `sys.path`, processing the various packages in some way.  apparmor steps in to prevent this from working, causing a crash.  Probably this is a crash for anyone who has ever run `pip install` or `sudo python setup.py install` to install python things from outside their OS.  The error I see, after modifying Twisted to raise the real exception rather than a misguided version error, is:

```
torbrowser-launcher 
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 29, in <module>
    import torbrowser_launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 31, in <module>
    from common import Common, SHARE
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 40, in <module>
    from twisted.internet import gtk2reactor
  File "/usr/lib/python2.7/dist-packages/twisted/__init__.py", line 54, in <module>
    _checkRequirements()
  File "/usr/lib/python2.7/dist-packages/twisted/__init__.py", line 34, in _checkRequirements
    from zope import interface
  File "/usr/lib/python2.7/dist-packages/zope/__init__.py", line 3, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3105, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 965, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3105, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2626, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2616, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1625, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1617, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1728, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/repoze.sphinx.autointerface-0.7.1.egg-info/namespace_packages.txt'
```

I can't decide if this is a security vulnerability in `pkg_resources` or not.  Perhaps if these files are on disk, you've already accepted them into your trust set.  Perhaps `torbrowser-launcher` can work around this my pruning `sys.path` before importing Twisted.  But that could be hard to do right.

**Comment by micahflee** [comment]
Sorry about being so negligent with this issue. In #224 I removed certificate pinning, which removes the zope.interface import, which I think just means that this isn't a problem any more. Can someone build from master and confirm?

**Comment by h01ger** [comment]
zope is not in the build-depends nor in the depends of the debian package:

Build-Depends: python-all (>= 2.7.3-4), debhelper (>= 9.20120909~), dh-python, dh-apparmor, lsb-release
Depends: ${misc:Depends}, ${python:Depends}, python-gtk2, python-psutil, python-twisted, python-lzma, gnupg, wmctrl, python-txsocksx (>= 1.13.0.1), python-parsley (>= 1.2), ca-certificates

also the last build + test of your master branch worked nicely as shown on https://jenkins.debian.net/view/torbrowser/job/torbrowser-launcher_test_on_unstable_amd64_from_git_branch_upstream_master/lastBuild/console so I think it's fine,

And finally: rgrep for the string "zope" in your master branch, only requirements.txt matches ;-)

**Comment by micahflee** [comment]
Thanks @h01ger
